### ISSUE TITLE
$rid field not being populated

### ISSUE THREAD

**Issue by ssanjay1** [palantir/osdk-ts#255]
The $rid field on objects is not populated and is always undefined on objects

**Comment by ericanderson** [comment]
Is this for 2? We intentionally make it not enumerable if it is there (so you wont see it if you console.log for example) to push people not to use it.

**Comment by ssanjay1** [comment]
Ah this was for 1.1, actually fixed with this, should have closed this issue https://github.com/palantir/osdk-ts/pull/261
