### ISSUE TITLE
Ontology Rid should be optional

### ISSUE THREAD

**Issue by ewitkon** [palantir/osdk-ts#279]
When using createClient we should allow developer not to pass an ontology Rid for cases where the client use used to access resource not bounded to the ontology like Datasets.

https://github.com/palantir/osdk-ts/blob/9aed809977fd73e2d0df7ae5683f88f4d8bfa37c/packages/client/src/createClient.ts#L37

**Comment by ericanderson** [comment]
Note to self, either implement this as:
- `createOntologyClient` and `createClient`
- `createClient` optionally takes an ontology rid, and thus calls to `client()` would take a second parameter for an ontology rid. Also could implement this as `client.withOntology(rid)`.

**Comment by ericanderson** [comment]
Likely blocks on #299

**Comment by ericanderson** [comment]
Also related: #301

**Comment by ericanderson** [comment]
Closing in favor of #375
