### ISSUE TITLE
Fix long type aggregations

### ISSUE THREAD

**Issue by ssanjay1** [palantir/osdk-ts#324]
Right now, longs come back as strings so we don't allow min/max aggs, even though gateway supports it. Once gateway is fixed to correctly return strings for an aggregation call on longs, fix the OSDK so that it will allow users to do a min/max aggregation on long properties

**Comment by ericanderson** [comment]
@ssanjay1 this is for 2.0 to ship?

**Comment by ssanjay1** [comment]
Nope, planned this is for 1.2.x

**Comment by bryantpark04** [comment]
I think after the type changes in #393 long type aggregations are already working as intended in the 2.0 client. Will fix for legacy client
