### ISSUE TITLE
Embed generator version in OSDKs

### ISSUE THREAD

**Issue by tdeitch** [palantir/osdk-ts#436]
We provide various sample apps and templates that users can use to get started with their generated SDKs. These templates assume certain things about the generated SDK (e.g. the shape of the public client auth object) that are only valid past certain versions of the SDK generator. If a user tries to use a template on a pre-existing SDK that they haven't regenerated in a while, they might get an error and not be able to figure out that they need to re-regenerate their SDK.

To avoid this, we could have our templates depend on a given version of the SDK generator, but in order to actually check that dependency the generator version will need to be propagated into the generated package somehow the sample apps can get to it.

**Comment by ericanderson** [comment]
On `main`, we now synchronize foundry-sdk-generator with the @osdk/client version which makes this really clean/easy to do. Closing out unless you think we need more.
