### ISSUE TITLE
Add ability to fuzzy search on a property

### ISSUE THREAD

**Issue by cacabo** [palantir/osdk-ts#907]
Currently for string filters we have the following options:

```typescript
"$startsWith" | "$containsAllTermsInOrder" | "$containsAnyTerm" | "$containsAllTerms"
```

To do a fuzzy-like search, I often write code like this, for example, to search for Staff Member Objects with names or IDs matching the provided `query`:

```typescript
if (query) {
      const term = query.toLocaleLowerCase()

      os = os.where({
        $or: [
          { firstName: { $startsWith: term } },
          { lastName: { $startsWith: term } },
          { id: { $startsWith: term } },
        ],
      })
}
```

I'd prefer to be able to have a query that fuzzy matches on a user's name properties instead of needing to handle splitting out terms and applying different casing myself.

Another alternative is to do token matching, but my understanding of that is you need a full token match. As an example, suppose my object Department has name "Hospital Main 1", i want the query "mai" to match, but it's hard to do that with the existing API provided.

> Prior code snippet here was a bit misleading because it used a few different casings of the string—it seems like the search endpoints are _not_ case sensitive, so the query "main" with match ["main", "Main", "MAIN"].

**Comment by ssanjay1** [comment]
https://github.com/palantir/osdk-ts/pull/1002
